version: "3"
services:
  pgsql:
    image: postgres:14.7
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - dev-net
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
     
  adminer:
      image: adminer
      restart: always
      networks:
          - dev-net
      ports:
          - 8080:8080

networks:
  dev-net:
    driver: bridge